sudo: require
language: node_js
services:
    - docker

before_install:
    - docker build -t p3ca/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run p3ca/react-test npm test -- --coverage

after_success:
    - docker build -t p3ca/multi-client ./client
    - docker build -t p3ca/multi-nginx ./nginx
    - docker build -t p3ca/multi-server ./server
    - docker build -t p3ca/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push p3ca/multi-client
    - docker push p3ca/multi-nginx
    - docker push p3ca/multi-server
    - docker push p3ca/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-989564378113
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
